services:
  - type: web
    name: get-site-styles-api
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm run api:build
    startCommand: pnpm run api:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_SECRET_KEY
        generateValue: true
      - key: ADMIN_API_KEY
        generateValue: true
      - key: DEFAULT_API_KEYS
        value: "demo-key-1,demo-key-2"
      - key: CORS_ORIGIN
        value: "*"
      - key: API_RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: API_RATE_LIMIT_MAX_REQUESTS
        value: "100"
    healthCheckPath: /api/v1/health
    autoDeploy: true 